# Live Coding Exercise: Plot MNIST Digits

---
In this exercise, we'll explore classification of handwritten digits from the MNIST dataset. **Please follow along in your own notebook.**

Goals are as follows:

- Load the MNIST dataset
- Understand how the MNIST dataset is organized
- Plot MNIST digits and view their associated labels

We'll begin by importing required libraries:

- `numpy` for efficient math operations
- `matplotlib` for visualization/plotting
- `tensorflow` will give us easy access to MNIST

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

### Loading MNIST

The data are already broken down into:

1. a development set, which should be used for training and validation
2. a test set, which should be used to evaluate performance

For now, we'll just take a look at the first few digits in the development set.

In [2]:
# Load MNIST
(x_dev, y_dev), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

print('There are', len(x_dev), 'training images.')
print('There are', len(x_test), 'test images.')

There are 60000 training images.
There are 10000 test images.


## Explore the shape and size of the data

Let's take a look how the data are organized...

## Count how many examples of each digit are present

## Plot the first few images (and their labels)

## Flatten and Un-Flatten Digits

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
a_flat = a.flatten()
print(a_flat)

[1 2 3 4 5 6 7 8 9]


In [7]:
print(a_flat.reshape(3, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
